<?php

namespace BlogBundle\Repository;

/**
 * UserauthRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserauthRepository extends \Doctrine\ORM\EntityRepository
{
}
